### ISSUE TITLE
Demo Project Not Run 

### ISSUE THREAD

**Issue by DipakCygnux** [flashphoner/wcs-android-sdk-samples#17]
Demo project is not working ,show this error
![image](https://user-images.githubusercontent.com/116353104/202097688-1d656b22-6f25-4b21-ad69-6ec8aa97be87.png)

**Comment by flashphoner** [comment]
Please make sure you've read the doc carefully and done all the steps (especially step 3): [Preparing examples for building](https://docs.flashphoner.com/display/ANDROIDSDK11EN/Overview#Overview-Preparingexamplesforbuilding)

**Comment by DipakCygnux** [comment]
follow same step but show same error

**Comment by DipakCygnux** [comment]
documentation not  show Step 3 , first show you show your doc...

**Comment by DipakCygnux** [comment]
![image](https://user-images.githubusercontent.com/116353104/202114923-8d94f697-11e7-4ead-af82-92e781b4980d.png)
not show 3 step

**Comment by flashphoner** [comment]
Please don't duplicate a messages from [the forum topic](https://forum.flashphoner.com/threads/demo-project-not-run.14473/)
