### ISSUE TITLE
Latest Android SDK Last Frame Not Cleaning

### ISSUE THREAD

**Issue by patelakshay13890** [flashphoner/wcs-android-sdk-samples#7]
I am using Latest Android FlashPhoner SDK.. 
But in that Last Frame Cleaning Code not working but it was working on previous SDK version..
So please help me out...

**Comment by flashphoner** [comment]
> I am using Latest Android FlashPhoner SDK..
> But in that Last Frame Cleaning Code not working but it was working on previous SDK version..
> So please help me out...

WebRTC library (libjinge-peerconnection) was upsated in Android SDK 1.1. So last frame clearing using SurfaceViewRenderer.release() stops working. Please use a following workaround:
1. Before creating a Stream object, make renderer visible
```
        /**
         * Stream playback will be started when Play button is clicked.
         */
        mPlayButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                mPlayButton.setEnabled(false);
                if (mPlayButton.getTag() == null || Integer.valueOf(R.string.action_play).equals(mPlayButton.getTag())) {
                    // Make remoteRender visible
                    remoteRender.setVisibility(View.VISIBLE);

                    /**
                     * The options for the stream to play are set.
                     * The stream name is passed when StreamOptions object is created.
                     */
                    StreamOptions streamOptions = new StreamOptions(mPlayStreamView.getText().toString());

                    /**
                     * Stream is created with method Session.createStream().
                     */
                    playStream = session.createStream(streamOptions);
                    ...
```
2. After stream stopping, make renderer invisible
```
                    ... 
               } else {
                    /**
                     * Method Stream.stop() is called to stop playback of the stream.
                     */
                    playStream.stop();
                    playStream = null;
                    // Make remoteRender invisible
                    remoteRender.setVisibility(View.GONE);
                }
                ...
```

**Comment by patelakshay13890** [comment]
Thanks for Quick Response..
But in Latest SDK why Minimum SDK 26 ???
It's too high older SDK Min SDK Support was 21 So I am asking...

**Comment by flashphoner** [comment]
You can use Android SDK 1.0 for devices with SDK below 26, and Android SDK 1.1 for devices with SDK 26 and above.
The example source code is identical. The only difference is libjingle-peerconnection.jar version used in WCS Android SDK
