### ISSUE TITLE
Continue Log in Debug Mode

### ISSUE THREAD

**Issue by patelakshay13890** [flashphoner/wcs-android-sdk-samples#8]
I am getting below Error Log continuously in LogCat Android Studio : 

VUI bitstream already contains an optimal VUI.
W/packet_buffer.cc: (line 350): Received H.264-IDR frame (SPS: 0, PPS: 0). Treating as key frame since WebRTC-SpsPpsIdrIsH264Keyframe is disabled
network.cc: (line 483): Network change was observed

**Comment by flashphoner** [comment]
This seems like normal webrtc library behaviour while playing a stream
> W/packet_buffer.cc: (line 350): Received H.264-IDR frame (SPS: 0, PPS: 0). Treating as key frame since WebRTC-SpsPpsIdrIsH264Keyframe is disabled

This means frame of type 'I' was received without picture state chenge information inside. WebRTC specification supposes to treat this frame as key frame.

> network.cc: (line 483): Network change was observed

This means some network conditions changing
