### ISSUE TITLE
Android Sample App - Could not resolve symbol fpwcsapi

### ISSUE THREAD

**Issue by thinkgopal** [flashphoner/wcs-android-sdk-samples#9]
Hi,

I downloaded the Sample code from below link.

https://github.com/flashphoner/wcs-android-sdk-samples

But getting error "could not resolve symbol **fpwcsapi**". And **fp_wcs_api** project also not available in Sample code.

Please guide me to fix this. Awaiting for your early response to fix this as it's very urgent.

Thanks in advance.

Best Regards,
Gopal

**Comment by flashphoner** [comment]
Please check if you've done all the steps described in [this doc](https://docs.flashphoner.com/display/ANDROIDSDK11EN/Overview#Overview-Preparingexamplesforbuilding)

**Comment by thinkgopal** [comment]
pc@gopal:~/Gopal/KiaVc/RequiredSDKs/flashphoner/wcs-android-sdk-samples-1.1/export$ ./export.sh wcs-android-sdk-1.1.0.16-release.aar
bash: ./export.sh: Permission denied

**Comment by thinkgopal** [comment]
This issue fixed by the help of guided steps. Thank you for your early response and help.
